### ISSUE TITLE
Color contrast could use adjustment

### ISSUE THREAD

**Issue by nickbreaton** [wesbos/hyperterm-cobalt2-theme#10]
Hello Wes!

Thanks for everything you do. You are truly an awesome person! 

I started using this theme the other day because of your beautiful [VSCode theme](https://github.com/wesbos/cobalt2-vscode/). Because I have a colorful shell, I noticed some of the colors, mostly red, have a very poor contrast and are almost hard to look at. I found this weird as the VSCode theme actually includes a [terminal color set](https://github.com/wesbos/cobalt2-vscode/blob/0201f43b59af0764908d5c9718c6481ae3c77d86/theme/cobalt2.json#L228-L245), and that does not have this issue. I'm wondering why not just share the same colors across VSCode and here?

If you agree, I can put up a PR.

|Hyper with current colors|Hyper with VSCode colors|VSCode terminal|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3587605/30759240-7feea7c2-9fa3-11e7-953d-31a0a3b4c4ac.png)|![image](https://user-images.githubusercontent.com/3587605/30759243-84217202-9fa3-11e7-96cd-1f83e4fc48d7.png)|![image](https://user-images.githubusercontent.com/3587605/30759308-c1413028-9fa3-11e7-853f-417a98c8d007.png)|

Thanks again.

**Comment by wesbos** [comment]
Thats a good idea -want to submit a PR?

**Comment by nickbreaton** [comment]
@wesbos absolutely. I'll work on it shortly.

**Comment by nickbreaton** [comment]
@wesbos Would you want the colors to be copied over into the `index.js` file by hand? Or would you want to depend on the vscode package? 

I could introduce a build step so that the dev version builds off of the vscode package, but production installs would not have to.

**Comment by wesbos** [comment]
oops - please reopen if its still an issue
