### ISSUE TITLE
The color block does not render perfectly

### ISSUE THREAD

**Issue by huchenme** [wesbos/hyperterm-cobalt2-theme#12]
![screenshot](https://d2ffutrenqvap3.cloudfront.net/items/3y2t0N3r1d2l1X2P0W0V/Image%202018-02-15%20at%2011.31.07%20AM.png?v=a1bf0488)

Not sure why is that and how to fix it, any suggestions?

config files here: https://github.com/huchenme/dotfiles/tree/cobalt2

**Comment by wesbos** [comment]
I don't know either - I have this :(

**Comment by huchenme** [comment]
may I have a look at your files and look at the diff please?

**Comment by wesbos** [comment]
Mine does the same thing - I don't have any different settings.


![image](https://user-images.githubusercontent.com/176013/36312032-2a1c24d4-12fb-11e8-9ad2-bf8fa8e4d1ea.png)

**Comment by huchenme** [comment]
Thanks for letting me know
