### ISSUE TITLE
wickedBorder: false has no effect

### ISSUE THREAD

**Issue by richkeenan** [wesbos/hyperterm-cobalt2-theme#14]
Hey! I want to remove the `wickedBorder` so I set `wickedBorder: false,` in the hyper config file but it doesn't have an effect. Same with setting the colour.

I'm using Hyper 2.0.0 (stable) and hyperterm-cobalt2-theme (2.0.0).

Could it be a change in the hyper API making the config inaccessible?

**Comment by michael-harvey** [comment]
I'm using those exact versions and having no issues. Is it possible that you're setting those properties outside of the `config` object?

**Comment by skeltonm** [comment]
> I'm using those exact versions and having no issues. Is it possible that you're setting those properties outside of the `config` object?

I had the same issue when I first installed it.  After moving to the `config` section, it worked just fine.

**Comment by richkeenan** [comment]
@michael-harvey and @skeltonm Thanks, that was exactly it! I didn't realise there was more than just a `config` key in the settings
